# Generated by Django 4.0.7 on 2022-09-16 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('document_type', models.CharField(blank=True, max_length=70, null=True)),
                ('document_ref_number', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, help_text='Enter your address', max_length=100, null=True)),
                ('city', models.CharField(blank=True, help_text='Enter your city', max_length=20, null=True)),
                ('state', models.CharField(blank=True, help_text='Enter your state', max_length=20, null=True)),
                ('country', models.CharField(blank=True, help_text='Enter your country', max_length=20, null=True)),
                ('zip_code', models.CharField(blank=True, help_text='Enter your zipcode', max_length=20, null=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
