# Generated by Django 4.0.7 on 2022-09-16 13:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=200)),
                ('descriptions', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('features', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('sub_total_price', models.DecimalField(decimal_places=3, max_digits=5)),
                ('manufactured_by', models.CharField(max_length=50)),
                ('is_new', models.BooleanField(default=False)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('manufactured_year', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_class', models.CharField(max_length=20)),
                ('star_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('car_photo', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
    ]
