# Generated by Django 4.0.7 on 2022-09-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='category',
            new_name='vehicle_type',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='is_new',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(blank=True, choices=[('AUTOMATIC', 'Automatic'), ('MANUAL', 'Manual')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='star_rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
