# Generated by Django 4.0.7 on 2022-09-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_rename_category_vehicle_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='sub_total_price',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
    ]
